version: '2'
services:
  python:
    container_name: python_server
    restart: always
    volumes:
    - ./python_flask/:/app
    build: python_flask
    ports:
    - "5000:5000"
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./:/app
    # command: --init-file /app/init.sql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    links:
    - mysql:db
volumes:
  my-datavolume:
